module TildaRuby
  class Client < TildaRuby::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader publickey: String?

    attr_reader secretkey: String?

    attr_reader projects: TildaRuby::Resources::Projects

    attr_reader pages: TildaRuby::Resources::Pages

    attr_reader export: TildaRuby::Resources::Export

    private def auth_query: -> ::Hash[String, String]

    private def public_key_auth: -> ::Hash[String, String]

    private def secret_key_auth: -> ::Hash[String, String]

    def initialize: (
      ?publickey: String?,
      ?secretkey: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
