module TildaRuby
  class CssAsset = TildaRuby::Models::CssAsset

  class ExportRetrieveFullParams = TildaRuby::Models::ExportRetrieveFullParams

  class ExportRetrieveParams = TildaRuby::Models::ExportRetrieveParams

  class ImageMapping = TildaRuby::Models::ImageMapping

  class JsAsset = TildaRuby::Models::JsAsset

  class PageBody = TildaRuby::Models::PageBody

  class PageExportBody = TildaRuby::Models::PageExportBody

  class PageExportFull = TildaRuby::Models::PageExportFull

  class PageFull = TildaRuby::Models::PageFull

  class PageListParams = TildaRuby::Models::PageListParams

  class PageRetrieveFullParams = TildaRuby::Models::PageRetrieveFullParams

  class PageRetrieveParams = TildaRuby::Models::PageRetrieveParams

  class PageSummary = TildaRuby::Models::PageSummary

  class ProjectInfo = TildaRuby::Models::ProjectInfo

  class ProjectListItem = TildaRuby::Models::ProjectListItem

  class ProjectListParams = TildaRuby::Models::ProjectListParams

  class ProjectRetrieveParams = TildaRuby::Models::ProjectRetrieveParams
end
