module TildaRuby
  module Resources
    class Getpagefull
      def retrieve: (
        pageid: String,
        ?request_options: TildaRuby::request_opts
      ) -> TildaRuby::Models::getpagefull_retrieve_response

      def initialize: (client: TildaRuby::Client) -> void
    end
  end
end
