module Tilda
  class Error = Tilda::Models::Error

  class GetpageexportRetrieveParams = Tilda::Models::GetpageexportRetrieveParams

  class GetpagefullexportRetrieveParams = Tilda::Models::GetpagefullexportRetrieveParams

  class GetpagefullRetrieveParams = Tilda::Models::GetpagefullRetrieveParams

  class GetpageRetrieveParams = Tilda::Models::GetpageRetrieveParams

  class GetpageslistRetrieveParams = Tilda::Models::GetpageslistRetrieveParams

  class GetprojectinfoRetrieveParams = Tilda::Models::GetprojectinfoRetrieveParams

  class GetprojectslistListParams = Tilda::Models::GetprojectslistListParams

  class ImageMapping = Tilda::Models::ImageMapping
end
