module TildaRuby
  module Models
    type getprojectslist_list_response =
      TildaRuby::Models::GetprojectslistListResponse::UnionMember0
      | TildaRuby::Error

    module GetprojectslistListResponse
      extend TildaRuby::Internal::Type::Union

      type union_member0 =
        {
          result: ::Array[TildaRuby::Models::GetprojectslistListResponse::UnionMember0::Result],
          status: TildaRuby::Models::GetprojectslistListResponse::UnionMember0::status
        }

      class UnionMember0 < TildaRuby::Internal::Type::BaseModel
        attr_accessor result: ::Array[TildaRuby::Models::GetprojectslistListResponse::UnionMember0::Result]

        attr_accessor status: TildaRuby::Models::GetprojectslistListResponse::UnionMember0::status

        def initialize: (
          result: ::Array[TildaRuby::Models::GetprojectslistListResponse::UnionMember0::Result],
          status: TildaRuby::Models::GetprojectslistListResponse::UnionMember0::status
        ) -> void

        def to_hash: -> {
          result: ::Array[TildaRuby::Models::GetprojectslistListResponse::UnionMember0::Result],
          status: TildaRuby::Models::GetprojectslistListResponse::UnionMember0::status
        }

        type result = { id: String, descr: String, title: String }

        class Result < TildaRuby::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor descr: String

          attr_accessor title: String

          def initialize: (id: String, descr: String, title: String) -> void

          def to_hash: -> { id: String, descr: String, title: String }
        end

        type status = :FOUND

        module Status
          extend TildaRuby::Internal::Type::Enum

          FOUND: :FOUND

          def self?.values: -> ::Array[TildaRuby::Models::GetprojectslistListResponse::UnionMember0::status]
        end
      end

      def self?.variants: -> ::Array[TildaRuby::Models::getprojectslist_list_response]
    end
  end
end
