module TildaRuby
  module Models
    type page_export_body =
      {
        id: String,
        alias_: String,
        date: String,
        descr: String,
        featureimg: String,
        filename: String,
        html: String,
        img: String,
        projectid: String,
        published: String,
        sort: String,
        title: String,
        css: ::Array[TildaRuby::CssAsset],
        images: ::Array[TildaRuby::ImageMapping],
        js: ::Array[TildaRuby::JsAsset]
      }

    class PageExportBody < TildaRuby::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor alias_: String

      attr_accessor date: String

      attr_accessor descr: String

      attr_accessor featureimg: String

      attr_accessor filename: String

      attr_accessor html: String

      attr_accessor img: String

      attr_accessor projectid: String

      attr_accessor published: String

      attr_accessor sort: String

      attr_accessor title: String

      attr_reader css: ::Array[TildaRuby::CssAsset]?

      def css=: (::Array[TildaRuby::CssAsset]) -> ::Array[TildaRuby::CssAsset]

      attr_reader images: ::Array[TildaRuby::ImageMapping]?

      def images=: (
        ::Array[TildaRuby::ImageMapping]
      ) -> ::Array[TildaRuby::ImageMapping]

      attr_reader js: ::Array[TildaRuby::JsAsset]?

      def js=: (::Array[TildaRuby::JsAsset]) -> ::Array[TildaRuby::JsAsset]

      def initialize: (
        id: String,
        alias_: String,
        date: String,
        descr: String,
        featureimg: String,
        filename: String,
        html: String,
        img: String,
        projectid: String,
        published: String,
        sort: String,
        title: String,
        ?css: ::Array[TildaRuby::CssAsset],
        ?images: ::Array[TildaRuby::ImageMapping],
        ?js: ::Array[TildaRuby::JsAsset]
      ) -> void

      def to_hash: -> {
        id: String,
        alias_: String,
        date: String,
        descr: String,
        featureimg: String,
        filename: String,
        html: String,
        img: String,
        projectid: String,
        published: String,
        sort: String,
        title: String,
        css: ::Array[TildaRuby::CssAsset],
        images: ::Array[TildaRuby::ImageMapping],
        js: ::Array[TildaRuby::JsAsset]
      }
    end
  end
end
