module Tilda
  module Models
    type getprojectinfo_retrieve_response =
      Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0 | Tilda::Error

    module GetprojectinfoRetrieveResponse
      extend Tilda::Internal::Type::Union

      type union_member0 =
        {
          result: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::Result,
          status: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::status
        }

      class UnionMember0 < Tilda::Internal::Type::BaseModel
        attr_accessor result: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::Result

        attr_accessor status: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::status

        def initialize: (
          result: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::Result,
          status: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::status
        ) -> void

        def to_hash: -> {
          result: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::Result,
          status: Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::status
        }

        type result =
          {
            id: String,
            customcsstext: String,
            customdomain: String,
            descr: String,
            export_csspath: String,
            export_imgpath: String,
            export_jspath: String,
            favicon: String,
            indexpageid: String,
            :page404id => String,
            title: String,
            images: ::Array[Tilda::ImageMapping]
          }

        class Result < Tilda::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor customcsstext: String

          attr_accessor customdomain: String

          attr_accessor descr: String

          attr_accessor export_csspath: String

          attr_accessor export_imgpath: String

          attr_accessor export_jspath: String

          attr_accessor favicon: String

          attr_accessor indexpageid: String

          attr_accessor page404id: String

          attr_accessor title: String

          attr_reader images: ::Array[Tilda::ImageMapping]?

          def images=: (
            ::Array[Tilda::ImageMapping]
          ) -> ::Array[Tilda::ImageMapping]

          def initialize: (
            id: String,
            customcsstext: String,
            customdomain: String,
            descr: String,
            export_csspath: String,
            export_imgpath: String,
            export_jspath: String,
            favicon: String,
            indexpageid: String,
            page404id: String,
            title: String,
            ?images: ::Array[Tilda::ImageMapping]
          ) -> void

          def to_hash: -> {
            id: String,
            customcsstext: String,
            customdomain: String,
            descr: String,
            export_csspath: String,
            export_imgpath: String,
            export_jspath: String,
            favicon: String,
            indexpageid: String,
            :page404id => String,
            title: String,
            images: ::Array[Tilda::ImageMapping]
          }
        end

        type status = :FOUND

        module Status
          extend Tilda::Internal::Type::Enum

          FOUND: :FOUND

          def self?.values: -> ::Array[Tilda::Models::GetprojectinfoRetrieveResponse::UnionMember0::status]
        end
      end

      def self?.variants: -> ::Array[Tilda::Models::getprojectinfo_retrieve_response]
    end
  end
end
