module Tilda
  module Models
    type getpageslist_retrieve_response =
      Tilda::Models::GetpageslistRetrieveResponse::UnionMember0 | Tilda::Error

    module GetpageslistRetrieveResponse
      extend Tilda::Internal::Type::Union

      type union_member0 =
        {
          result: ::Array[Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::Result],
          status: Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::status
        }

      class UnionMember0 < Tilda::Internal::Type::BaseModel
        attr_accessor result: ::Array[Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::Result]

        attr_accessor status: Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::status

        def initialize: (
          result: ::Array[Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::Result],
          status: Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::status
        ) -> void

        def to_hash: -> {
          result: ::Array[Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::Result],
          status: Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::status
        }

        type result =
          {
            id: String,
            alias_: String,
            date: String,
            descr: String,
            featureimg: String,
            filename: String,
            img: String,
            projectid: String,
            published: String,
            sort: String,
            title: String
          }

        class Result < Tilda::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor alias_: String

          attr_accessor date: String

          attr_accessor descr: String

          attr_accessor featureimg: String

          attr_accessor filename: String

          attr_accessor img: String

          attr_accessor projectid: String

          attr_accessor published: String

          attr_accessor sort: String

          attr_accessor title: String

          def initialize: (
            id: String,
            alias_: String,
            date: String,
            descr: String,
            featureimg: String,
            filename: String,
            img: String,
            projectid: String,
            published: String,
            sort: String,
            title: String
          ) -> void

          def to_hash: -> {
            id: String,
            alias_: String,
            date: String,
            descr: String,
            featureimg: String,
            filename: String,
            img: String,
            projectid: String,
            published: String,
            sort: String,
            title: String
          }
        end

        type status = :FOUND

        module Status
          extend Tilda::Internal::Type::Enum

          FOUND: :FOUND

          def self?.values: -> ::Array[Tilda::Models::GetpageslistRetrieveResponse::UnionMember0::status]
        end
      end

      def self?.variants: -> ::Array[Tilda::Models::getpageslist_retrieve_response]
    end
  end
end
