module Tilda
  module Models
    type getpage_retrieve_params =
      { pageid: String } & Tilda::Internal::Type::request_parameters

    class GetpageRetrieveParams < Tilda::Internal::Type::BaseModel
      extend Tilda::Internal::Type::RequestParameters::Converter
      include Tilda::Internal::Type::RequestParameters

      attr_accessor pageid: String

      def initialize: (
        pageid: String,
        ?request_options: Tilda::request_opts
      ) -> void

      def to_hash: -> { pageid: String, request_options: Tilda::RequestOptions }
    end
  end
end
